# This is a configuration file for Cloudflare Pages.
# It's used by the `wrangler pages dev` command for local development.

# For production, it is strongly recommended to set environment variables
# and secrets in the Cloudflare dashboard rather than committing them here.

name = "llm-chat"
compatibility_date = "2024-03-26"

[vars]
# For local development, add your Abacus.ai API key here.
# IMPORTANT: For production, this should be set as a secret, not a plain text variable.
# Use the command: npx wrangler secret put ABACUS_API_KEY
ABACUS_API_KEY = "your-api-key-goes-here"
