name = "chatai2"
main = "src/index.js"
compatibility_flags = [ "nodejs_compat", "global_fetch_strictly_public" ]
compatibility_date = "2025-07-21"
workers_dev = false
account_id = "93e0a6dda0f48d77b387cae708297820"
routes = [
 { pattern = "http://chatai2.hwmnbn.me/", zone_id = "ff94bb317bdc9cf828f8821b5ded355d" },
 { pattern = "https://chatai2.hwmnbn.me/", zone_id = "ff94bb317bdc9cf828f8821b5ded355d" } 
]
[placement]
mode = "smart"
[ai]
binding = "AI"
[assets]
directory = "./public"
binding = "ASSETS"
# wrangler.toml (wrangler v4.26.1^)
[observability.logs]
enabled = true




