name = "chatai2"
main = "./src/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-07-21"
workers_dev = false
account_id = "93e0a6dda0f48d77b387cae708297820"
routes = [
 { pattern = "http://chatai2.hwmnbn.me/*", zone_id = "ff94bb317bdc9cf828f8821b5ded355d" },
 { pattern = "https://chatai2.hwmnbn.me/*", zone_id = "ff94bb317bdc9cf828f8821b5ded355d" } 
]
[placement]
mode = "smart"
[ai]
binding = "AI"
[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/src/*","/api/generate","/api/tags","/public/*"]
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true




